config/routes.rb
Rails.application.routes.draw do
  get 'addresses/index'
  get 'addresses/create'
  get 'addresses/update'
  root to: "homes#top"

  devise_for :admin, controllers:{
    sessions: "admins/sessions",
    registrations: "admins/registrations"
  }

  devise_for :end_users, controllers:{
    sessions: "end_users/sessions",
    registrations: "end_users/registrations"
  }

  resource :customers,only:[:show,:update,:edit]
  get "/customers/confirm" => "customers#confirm" ,as: "confirm_customers"
  patch "/customers/unsubscribed" => "customers#unsubscribed" ,as: "unsubscribed_customers"
  
  
  resources :addresses, only:[:index,:create,:update,:destroy,:edit]
  
  resources :items, only:[:index, :show]

  resources :cart_items, only:[:index,:update, :create, :destroy]
  delete "/cart_items" => "cart_items#destroy_all", as: "destroy_all_cart_items"

  post "/orders/confirm" => "orders#confirm", as: "confirm_order"
  get "/orders/complete" => "orders#complete", as: "complete_order"
  resources :orders, only:[:index, :show, :create, :new]

  namespace :admin do
    root to: "homes#top"
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :show, :edit, :update, :new, :create]
    get 'search' => "items#search", as: "search"
    resources :genres, only:[:index, :create, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @end_users=EndUser.all
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show

  end

  def edit
    @end_user=current_end_user
  end

  def update
    @end_user=current_end_user
    if @end_user.update(end_user_params)
      redirect_to customers_path
      flash[:notice]="会員情報を更新しました"
    else
      render :edit
    end
  end

  def confirm
    @end_user=current_end_user
  end

  def unsubscribed
    end_user=current_end_user
    end_user.update(is_unsubscribed: true)
    # session_reset→ログアウトする
    reset_session
    flash[:notice]="ありがとうございました。またのご利用を心よりお待ちしています。"
    redirect_to root_path
  end

  private

  def end_user_params
    params.require(:end_user).permit(:first_name,:family_name,:first_name_kana,:family_name_kana,:email,:zip_code,:address,:phone_number,:is_unsubscribed)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/confirm.html.erb
<div class="container my-5 text-center">
  <!--<div class="row">-->
  <!--  <div class="col offset-4">-->

      <div class="row">
        <h2 class="mx-auto">本当に退会しますか？</h2>
      </div>

      <div class="row mt-4">
        <div class="mx-auto">
          退会すると、会員登録情報や<br>
          これまでの購入履歴が閲覧できなくなります。<br>
          退会する場合には、「退会する」をクリックしてください。
        </div>
      </div>

      <%= form_with model:@end_user, url: unsubscribed_customers_path,locol:true do |f| %>
        <div class="row my-5">
          <div class="col-4 offset-2">
            <%= link_to "退会しない", customers_path, class:"btn btn-primary" %>
          </div>
          <div class="col-4">
            <%= f.submit "退会する","data-confirm" => "本当に退会しますか？",class:"btn btn-danger" %>
          </div>
        </div>
      <% end %>

  <!--  </div>-->
  <!--</div>-->



</div>

app/views/customers/edit.html.erb
<div class="container px-5 px-sm-0">
  <div class="row p-3 m-3">
    <div class="grey-box px-3">
      <h3>会員情報編集</h3>
    </div>
  </div>

  <% if @end_user.errors.any? %>
    <%=  render "layouts/errors",obj:@end_user %>
  <% end %>

  <%= form_with model: @end_user, url: customers_path, local: true do |f| %>
    <div class="row m-2">
      <div class="col-3">
        名前
      </div>
      <div class="col-3">
        <%= f.text_field :family_name, autofocus: true %>
      </div>
      <div class="col-3">
        <%= f.text_field :first_name, autofocus: true %>
      </div>
    </div>

    <div class="row m-2">
      <div class="col-3">
        フリガナ
      </div>
      <div class="col-3">
        <%= f.text_field :family_name_kana, autofocus: true %>
      </div>
      <div class="col-3">
        <%= f.text_field :first_name_kana, autofocus: true %>
      </div>
    </div>

    <div class="row m-2">
      <div class="col-3">
        郵便番号
      </div>
      <div class="col-3">
        <%= f.text_field :zip_code, autofocus: true %>
      </div>
    </div>

    <div class="row m-2">
      <div class="col-3">
        住所
      </div>
      <div class="col-6">
        <%= f.text_field :address, autofocus: true, class:"full-width"%>
      </div>
    </div>

    <div class="row m-2">
      <div class="col-3">
        電話番号
      </div>
      <div class="col-3">
        <%= f.text_field :phone_number, autofocus: true %>
      </div>
    </div>

    <div class="row m-2">
      <div class="col-3">
        メールアドレス
      </div>
      <div class="col-3">
        <%= f.text_field :email, autofocus: true %>
      </div>
    </div>

    <div class="row mt-4 m-2 ">
      <div class="col-3 offset-2">
        <div class="actions">
          <%= f.submit "編集内容を保存" ,class:"btn btn-success px-2" %>
        </div>
      </div>
      <div class="col-3">
          <%= link_to "退会する", confirm_customers_path, class:"btn btn-danger" %>
      </div>
    </div>
  <% end %>

app/views/customers/show.html.erb
<div class="container px-5 px-sm-0">

  <div class="row mt-5">
    <div class="col-auto offset-2">
      <div class="grey-box mb-auto px-2">
        <h2>マイページ</h2>
      </div>
    </div>
  </div>

  <div class="row py-3">
    <div class="col-3">
      <h3>登録情報</h3>
    </div>
    <div class="col-3">
      <%= link_to "編集する", edit_customers_path, class:"btn btn-success px-5" %>
    </div>
  </div>

  <div class="row py-3">
    <div class="col-9">
      <table class="table table-bordered mb-auto">
        <tr>
          <td class="grey-box">氏名</td>
          <td><%= current_end_user.family_name %>　<%= current_end_user.first_name %></td>
        </tr>
        <tr>
          <td class="grey-box">カナ</td>
          <td><%= current_end_user.family_name_kana %>　<%= current_end_user.first_name_kana %></td>
        </tr>
        <tr>
          <td class="grey-box">郵便番号</td>
          <td><%= current_end_user.zip_code %></td>
        </tr>
        <tr>
          <td class="grey-box">住所</td>
          <td><%= current_end_user.address %></td>
        </tr>
        <tr>
          <td class="grey-box">電話番号</td>
          <td><%= current_end_user.phone_number %></td>
        </tr>
        <tr>
          <td class="grey-box">メールアドレス</td>
          <td><%= current_end_user.email %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row py-3">
    <div class="col-3">
      <h3>配送先</h3>
    </div>
    <div class="col-3">
      <%= link_to "一覧を見る",addresses_path, class:"btn btn-primary px-5" %>
    </div>
  </div>

  <div class="row py-3">
    <div class="col-3">
      <h3>注文履歴</h3>
    </div>
    <div class="col-3">
      <%= link_to "一覧を見る",root_path, class:"btn btn-primary px-5" %>
    </div>
  </div>
</div>