config/routes.rb
Rails.application.routes.draw do
  get 'addresses/index'
  get 'addresses/create'
  get 'addresses/update'
  root to: "homes#top"

  devise_for :admin, controllers:{
    sessions: "admins/sessions",
    registrations: "admins/registrations"
  }

  devise_for :end_users, controllers:{
    sessions: "end_users/sessions",
    registrations: "end_users/registrations"
  }

  resource :customers,only:[:show,:update,:edit]
  get "/customers/confirm" => "customers#confirm" ,as: "confirm_customers"
  patch "/customers/unsubscribed" => "customers#unsubscribed" ,as: "unsubscribed_customers"
  
  
  resources :addresses, only:[:index,:create,:update,:destroy,:edit]
  
  resources :items, only:[:index, :show]

  resources :cart_items, only:[:index,:update, :create, :destroy]
  delete "/cart_items" => "cart_items#destroy_all", as: "destroy_all_cart_items"

  post "/orders/confirm" => "orders#confirm", as: "confirm_order"
  get "/orders/complete" => "orders#complete", as: "complete_order"
  resources :orders, only:[:index, :show, :create, :new]

  namespace :admin do
    root to: "homes#top"
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :show, :edit, :update, :new, :create]
    get 'search' => "items#search", as: "search"
    resources :genres, only:[:index, :create, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :end_user
  belongs_to :item

  def each_item_total_price
    self.item.price*self.amount
  end
 
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
    cart_item = CartItem.new(cart_item_params)
    cart_item.end_user_id = current_end_user.id
    #すでに存在する→amountに加算するだけ　新規投稿→table作成
    if cart_item.amount>0
      if item_already_registered?(cart_item.item_id)
        add_cart_item = CartItem.find_by(end_user_id: current_end_user, item_id: cart_item.item_id)
        add_cart_item.amount += cart_item.amount
        add_cart_item.update(amount: add_cart_item.amount)
        redirect_to cart_items_path
      else
        cart_item.save
        redirect_to cart_items_path
      end
    else
      flash[:error]="適切な数量を入力してください"
      redirect_to item_path(params[:cart_item][:item_id].to_i)
    end
  end

  def index
    @cart_items=current_end_user.cart_items.all
    @total=0
    @cart_items.each do |cart_item|
      @total+=cart_item.item.price*cart_item.amount
    end
  end

  def destroy
    cart_item=CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path, notice: "カート商品を削除しました"
  end

  def destroy_all
    cart_items=current_end_user.cart_items.all
    cart_items.destroy_all
    redirect_to cart_items_path, notice: "カート内商品を全て削除しました"
  end

  def update
    cart_item = CartItem.find(params[:id])
    # byebug
    if params[:cart_item][:amount].to_i >0
      cart_item.update(cart_item_params)
      redirect_to cart_items_path, notice: "商品数量を変更しました"
    else
      @cart_items=current_end_user.cart_items.all
      @total=0
      @cart_items.each do |cart_item|
        @total+=cart_item.item.price*cart_item.amount
      end
      flash[:error]="適切な数量を入力してください"
      render :index
    end
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:amount,:item_id)
  end

  # 現在のユーザーと該当アイテムのものがすでにcart_item内に存在するかを判定する
  def item_already_registered?(each_item_id)
    CartItem.where(end_user_id: current_end_user.id, item_id: each_item_id).exists?
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<div class="container mx-auto my-5 px-sm-0">
  <div class="row ">
    <div class="col-4 grey-box text-center fw-bold">
      <h2>ショッピングカート</h2>
    </div>

    <div class="col-2 offset-6">
      <%= link_to "カートを空にする",destroy_all_cart_items_path, method: :delete, class:"btn btn-danger px-3", data:{confirm: "本当に削除しますか？"}%>
    </div>
  </div>

  <div class="row mt-5">
    <table class="table">
      <thead>
        <tr class="table-secondary">
          <th style="width:40%">商品名</th>
          <th style="width:15%">単価(税込み)</th>
          <th style="width:15%">数量</th>
          <th style="width:15%">小計</th>
          <th style="width:15%"></th>
        </tr>
      </thead>
      <tbody>
        <% @cart_items.each do |cart_item| %>
          <tr>
            <td class="flex flex-row">
              <%= attachment_image_tag cart_item.item, :image,:fill ,50, 50, format:"jpeg",fallback:"no_products_found.png", size:"50x50" %>
              <strong class="item-name"><%= cart_item.item.name %></strong>
            </td>
            <td><%= cart_item.item.price.to_s(:delimited) %></td>
            <%= form_with model: cart_item, url: cart_item_path(cart_item), method: :patch, local: true do |f| %>
              <td class="flex flex-row">
                <%= f.hidden_field :item_id, :value => cart_item.item_id %>
                <%= f.number_field :amount, style: "width:50%" %>
                <%= f.submit "変更", class:"btn btn-success px-1" %>
              </td>
            <% end %>
            <td>
              <%= (cart_item.item.price * cart_item.amount).to_s(:delimited) %>
            </td>
            <td>
              <%= link_to "削除する", cart_item_path(cart_item), method: :delete, class:"btn btn-danger px-3" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row">
    <div class="col-3 offset-1">
      <%= link_to "買い物を続ける", root_path, class:"btn btn-primary px-3" %>
    </div>
    <div class="col-3 offset-4">
      <table class="table">
        <tr>
          <th class="table-secondary">合計金額</th>
          <td><%= @total.to_s(:delimited) %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col d-flex justify-content-center">
      <%= link_to "情報入力に進む",new_order_path, class:"btn btn-success px-3" %>
    </div>
  </div>

</div>