config/routes.rb
Rails.application.routes.draw do
  get 'addresses/index'
  get 'addresses/create'
  get 'addresses/update'
  root to: "homes#top"

  devise_for :admin, controllers:{
    sessions: "admins/sessions",
    registrations: "admins/registrations"
  }

  devise_for :end_users, controllers:{
    sessions: "end_users/sessions",
    registrations: "end_users/registrations"
  }

  resource :customers,only:[:show,:update,:edit]
  get "/customers/confirm" => "customers#confirm" ,as: "confirm_customers"
  patch "/customers/unsubscribed" => "customers#unsubscribed" ,as: "unsubscribed_customers"
  
  
  resources :addresses, only:[:index,:create,:update,:destroy,:edit]
  
  resources :items, only:[:index, :show]

  resources :cart_items, only:[:index,:update, :create, :destroy]
  delete "/cart_items" => "cart_items#destroy_all", as: "destroy_all_cart_items"

  post "/orders/confirm" => "orders#confirm", as: "confirm_order"
  get "/orders/complete" => "orders#complete", as: "complete_order"
  resources :orders, only:[:index, :show, :create, :new]

  namespace :admin do
    root to: "homes#top"
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :show, :edit, :update, :new, :create]
    get 'search' => "items#search", as: "search"
    resources :genres, only:[:index, :create, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre

  has_many :cart_items
  has_many :order_details

  validates :name, presence: true
  validates :explanation, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  
  def self.search(search)
    if search
      Item.where(["name LIKE ?", "%#{search}%"])
    else
      Item.all
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items=Item.all
  end

  def new
    @item=Item.new
    @genres=Genre.all
  end

  def create
    @item=Item.new(item_params)
    if @item.save
      flash[:notice] = "商品の登録に成功しました"
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
      flash[:notice]="商品情報を更新しました"
    else
      render :edit
    end
  end
  
  def search
    @items=Item.search(params[:keyword])
    @keyword = params[:keyword]
    render "index"
  end 
  
  private

  def item_params
    params.require(:item).permit(:name,:genre_id,:explanation,:image,:price,:is_sold)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @genres=Genre.all
    if params[:genre_id]
      @genre=Genre.find(params[:genre_id])
      @items=@genre.items.where(is_sold: true)
    else
      @items=Item.where(is_sold: true)
    end
  end

  def show
    @item=Item.find(params[:id])
    @cart_item=CartItem.new
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<div class="container mx-auto px-sm-0">
<div class="row">
  <div class="col-3">
    <table class="table">
      <thead>
        <th><p class="text-center">ジャンル検索</p></th>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= link_to genre.name, items_path(genre_id: genre.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-8 offset-1">
    <div class="row mt-5 my-5">
      <div class="col-3 text-center fw-bold">
        <% if @genre %>
          <h2><%= @genre.name %>一覧</h2>
        <% else %>
          <h2>商品一覧</h2>
        <% end %>
      </div>
      <div class="col align-self-end">
        (全<%= @items.count %>件)
      </div>
    </div>

    <div class="row">
      <% @items.each do |item| %>
      <div class="col-lg-3 col-6">
        <div class="item-container">
          <%= link_to item_path(item) do %>
            <%= attachment_image_tag item, :image, :fill, 200, 100, format:"jpeg",fallback:"no_products_found.png", size:"200x100", class:"my-2" %>
          <% end %>
          <p class="font-weight-bold"><%= item.name %></p>
          <p>¥<%= item.price.to_s(:delimited) %></p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>


</div>

app/views/items/show.html.erb
<div class="container mx-auto my-5 px-sm-0">
  <div class="row py-5">
    <div class="col-5 offset-1">
      <%= attachment_image_tag @item, :image, :fill, 560, 280, format:"jpeg",fallback:"no_products_found.png", size:"400x200", class:"attachment-image" %>
    </div>

    <div class="col-5 offset-1">
      <h1><%= @item.name %> </h1>

      <div class="mt-4 mb-5">
        <p style="font-size: 20px"><%= @item.explanation %></p>
      </div>

      <div class="price-container">
        <p><span class="price font-weight-bold">¥ <%= @item.price.to_s(:delimited) %></span> (税込)</p>
      </div>

      <%= form_with model: @cart_item, url: cart_items_path, method: "post", local: true do |f| %>
        <%= f.hidden_field :item_id, :value => @item.id  %>
        <div class="row my-5">
          <div class="col-4">
            <%= f.number_field :amount ,placeholder: "個数選択" %>
          </div>
          <div class="col-4 offset-2">
            <%= f.submit "カートに入れる", class:"btn btn-success px-4" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>