config/routes.rb
Rails.application.routes.draw do
  get 'addresses/index'
  get 'addresses/create'
  get 'addresses/update'
  root to: "homes#top"

  devise_for :admin, controllers:{
    sessions: "admins/sessions",
    registrations: "admins/registrations"
  }

  devise_for :end_users, controllers:{
    sessions: "end_users/sessions",
    registrations: "end_users/registrations"
  }

  resource :customers,only:[:show,:update,:edit]
  get "/customers/confirm" => "customers#confirm" ,as: "confirm_customers"
  patch "/customers/unsubscribed" => "customers#unsubscribed" ,as: "unsubscribed_customers"
  
  
  resources :addresses, only:[:index,:create,:update,:destroy,:edit]
  
  resources :items, only:[:index, :show]

  resources :cart_items, only:[:index,:update, :create, :destroy]
  delete "/cart_items" => "cart_items#destroy_all", as: "destroy_all_cart_items"

  post "/orders/confirm" => "orders#confirm", as: "confirm_order"
  get "/orders/complete" => "orders#complete", as: "complete_order"
  resources :orders, only:[:index, :show, :create, :new]

  namespace :admin do
    root to: "homes#top"
    resources :customers, only:[:index, :show, :edit, :update]
    resources :items, only:[:index, :show, :edit, :update, :new, :create]
    get 'search' => "items#search", as: "search"
    resources :genres, only:[:index, :create, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :end_user

  validates :name, presence: true
  validates :address, presence: true
  validates :zip_code, presence: true

  def address_info
    "〒#{self.zip_code} #{self.address}  #{self.name}"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :end_user
  belongs_to :item

  def each_item_total_price
    self.item.price*self.amount
  end
 
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :orders
  has_many :addresses, dependent: :destroy

  validates :first_name, presence: true
  validates :first_name_kana, presence: true
  validates :family_name, presence: true
  validates :family_name_kana, presence: true
  validates :zip_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def active_for_authentication?
    super && (self.is_unsubscribed == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    validates :name, presence: true
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre

  has_many :cart_items
  has_many :order_details

  validates :name, presence: true
  validates :explanation, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  
  def self.search(search)
    if search
      Item.where(["name LIKE ?", "%#{search}%"])
    else
      Item.all
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :end_user
  has_many :order_details
  accepts_nested_attributes_for :order_details

  enum status:{ waiting_payment: 0, checking_payment: 1, making: 2, ready_to_shipping: 3, shipped: 4 }
  enum payment_method:{ credit_card: 0, bank_transfer: 1, paypay: 2}

  def total_amount
    total_amount=0
    self.order_details.each do |order_detail|
      total_amount+=order_detail.amount
    end
    return total_amount
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum production_status:{ not_startable: 0, waiting_for_production: 1, producting: 2, producted: 3}
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items=Item.order(created_at: :desc).limit(5)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @genres=Genre.all
    if params[:genre_id]
      @genre=Genre.find(params[:genre_id])
      @items=@genre.items.where(is_sold: true)
    else
      @items=Item.where(is_sold: true)
    end
  end

  def show
    @item=Item.find(params[:id])
    @cart_item=CartItem.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :is_cart_empty?, only:[:new, :create, :confirm]

  def new
    @order = Order.new
    @addresses = current_end_user.addresses
  end

  def create
    # orderのsave
    order=Order.new(order_params)
    order.end_user_id=current_end_user.id
    byebug
    if order.save
      current_end_user.cart_items.each do |cart_item|
        order_detail=OrderDetail.new
        order_detail.order_id=order.id
        order_detail.item_id=cart_item.item_id
        order_detail.price=cart_item.item.price
        order_detail.amount=cart_item.amount
        order_detail.save
      end
      current_end_user.cart_items.destroy_all
      redirect_to complete_order_path
    end
  end

  def index
  end

  def show
  end

  def confirm
    shipping_destination=params[:order][:destination]
    @order=Order.new(order_params)
    @order.end_user_id=current_end_user.id
    @order.shipping_fee=800
    puts shipping_destination
    puts current_end_user

    case shipping_destination.to_i
    when 0
      @order.address=current_end_user.address
      @order.zip_code=current_end_user.zip_code
      @order.address_name=current_end_user.family_name+current_end_user.first_name
    when 1
      address=Address.find(params[:order][:address_id])
      @order.address=address.address
      @order.zip_code=address.zip_code
      @order.address_name=address.name
    when 2
    end

    @cart_items = current_end_user.cart_items
    @total=0
    @cart_items.each do |cart_item|
      @total+=cart_item.item.price*cart_item.amount
    end
    @order.total_price=@order.shipping_fee+@total

  end

  def complete
  end


  def is_cart_empty?
    if !current_end_user.cart_items.any? or current_end_user.cart_items.where(amount:0).count >= 1
      flash[:error]="カート内の商品がないまたは不適切です"
      redirect_to cart_items_path
    end
  end

  private

  def order_params
    params.require(:order).permit(:payment_method, :address, :zip_code, :address_name, :shipping_fee, :total_price)
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<!--end_user ログイン、adminログイン、ログインしていないの3パターン必要-->
<nav class="navbar navbar-expand-lg navbar-dark bg-light">
  <div class="container">
    <% if admin_signed_in? %>
      <a class="navbar-brand" href="/admin/"><div class="logo-image"></div></a>
    <% else %>
      <a class="navbar-brand" href="/"><div class="logo-image"></div></a>
    <% end %>
    <!--ユーザー氏名表示-->
    <div class="navbar-text text-dark">
      <% if end_user_signed_in? %>
        <p>ようこそ、<%= current_end_user.family_name %><%=current_end_user.first_name %>さん！</p>
      <% end %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse show flex-md-column" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li>
              <%= link_to "商品一覧", admin_items_path, class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
            <li>
              <%= link_to "会員一覧", admin_customers_path, class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
            <li>
              <%= link_to "会員注文履歴一覧", admin_orders_path, class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
            <li>
              <%= link_to "ジャンル一覧", admin_genres_path, class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
          <% elsif end_user_signed_in? %>
            <li>
              <%= link_to "マイページ", customers_path, class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
            <li>
              <%= link_to "商品一覧", items_path, class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
            <li>
              <%= link_to "カート", cart_items_path, class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_end_user_session_path,method: :delete, class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
          <% else %>
            <li>
              <%= link_to "About", root_path, class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
            <li>
              <%= link_to "商品一覧", items_path, class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
            <li>
              <%= link_to "新規登録", new_end_user_registration_path , class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
            <li>
              <%= link_to "ログイン", new_end_user_session_path, class:"btn btn-outline-secondary btn-block nav-link text-light" %>
            </li>
          <% end %>
        </ul>
        <!--検索フォーム-->
        <% if admin_signed_in? %>
          <ul class="navbar-nav ml-auto">
            <%= form_with url: admin_search_path, method: :get, local: true do |f| %>
              <%= f.text_field :keyword, value: @keyword, placeholder:"search" %>
              <%= f.submit "検索", class:"btn btn-primary mx-2"%>
            <% end %>
          </ul>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="bg-light">
    <%= render "layouts/header" %>
  </header>
  <body>
    <% if notice %>
      <div class="px-5 py-2 mx-5">
        <p id="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class="px-5 py-2 mx-5">
        <p id="error"><%= flash[:error] %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
  <footer>
    <div class="container mt-5">
    	<div class="row">
      </div>
    </div>
  </footer>
</html>